// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumInfo } from "./AlbumInfo";

export type AlbumPayload = { 
/**
 * With its tracks; `null` before the first album fetch.
 */
album: AlbumInfo | null, };
