// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistRef } from "./ArtistRef";
import type { TrackInfo } from "./TrackInfo";

export type AlbumInfo = { id: string | null, uri: string | null, name: string, artists: Array<ArtistRef>, 
/**
 * One of `"album"`, `"single"`, `"compilation"` (lowercased), when known.
 */
album_type: string | null, release_date: string | null, total_tracks: number | null, image_url: string | null, 
/**
 * Populated when mapped from a full album; empty for simplified albums.
 */
tracks: Array<TrackInfo>, };
