// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A navigable reference to an artist: optional Spotify id plus display name.
 *
 * Reused by [`TrackInfo`], [`AlbumInfo`], and [`ArtistInfo`]. `id` is `None`
 * for local/unknown sources or when the API omits it.
 */
export type ArtistRef = { id: string | null, name: string, };
