// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistInfo = { id: string | null, uri: string | null, name: string, image_url: string | null, };
