// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export type ClientMessage = { "type": "action", action: Action, } | { "type": "quit" };
