// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A color in the terminal's color model. Named variants follow the 16 ANSI
 * palette entries; `Reset` is the frontend's default foreground/background.
 *
 * The serde derives are the *wire* representation for the shared action
 * vocabulary (`core/action`) and future frontend codegen. They are unrelated
 * to the on-disk `config.yml` format, which stays hand-parsed by
 * [`parse_theme_item`] / [`color_to_string`].
 */
export type Color = "Reset" | "Black" | "Red" | "Green" | "Yellow" | "Blue" | "Magenta" | "Cyan" | "Gray" | "DarkGray" | "LightRed" | "LightGreen" | "LightYellow" | "LightBlue" | "LightMagenta" | "LightCyan" | "White" | { "Rgb": [number, number, number] } | { "Indexed": number };
