// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What [`Action::CopyUrl`] copies; both address the item playing now (an
 * episode gives its episode / show URL).
 */
export type CopyTarget = "CurrentSong" | "CurrentAlbum";
