// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceInfo = { id: string | null, name: string, 
/**
 * Lowercased DeviceType name, e.g. `"computer"`, `"smartphone"`, `"speaker"`.
 */
kind: string, is_active: boolean, volume_percent: number | null, };
