// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoverTimeRange } from "./DiscoverTimeRange";

/**
 * Which Discover row [`Action::OpenDiscover`] activates.
 */
export type DiscoverTarget = "ArtistsMix" | { "TopTracks": DiscoverTimeRange };
