// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time range for Top Tracks/Artists in Discover feature
 */
export type DiscoverTimeRange = "Short" | "Medium" | "Long";
