// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscoverTimeRange } from "./DiscoverTimeRange";
import type { TrackInfo } from "./TrackInfo";

export type DiscoverPayload = { 
/**
 * False without a Spotify session.
 */
available: boolean, 
/**
 * A fetch runs; the page cannot tell which list it is for.
 */
loading: boolean, 
/**
 * The range `top_tracks` belongs to; `null` before the first landing.
 */
top_tracks_range: DiscoverTimeRange | null, top_tracks: Array<TrackInfo>, artists_mix: Array<TrackInfo>, 
/**
 * False once this app key lost the artist top-tracks endpoint.
 */
artists_mix_available: boolean, 
/**
 * The ids among both lists that are in Liked Songs.
 */
liked_ids: Array<string>, };
