// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-domain revisions that move only when that domain's displayed state changed.
 */
export type DisplayRevisions = { route: number, status: number, source: number, theme: number, playback: number, party: number, devices: number, search: number, lyrics: number, artist: number, library: number, queue: number, };
