// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResumePointInfo } from "./ResumePointInfo";

export type EpisodeInfo = { id: string | null, uri: string | null, name: string, duration_ms: number, 
/**
 * Parent show name. Populated from a full episode (e.g. a queue item);
 * empty for simplified episodes that are already shown within their show's
 * context (the show-episodes list).
 */
show_name: string, description: string, release_date: string, is_playable: boolean, 
/**
 * Resume/played state, when the source provides it (e.g. the show-episodes
 * list). Drives the "fully played" marker and resume-position display.
 */
resume_point: ResumePointInfo | null, image_url: string | null, };
