// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayRevisions } from "./DisplayRevisions";

export type HelloPayload = { version: string, 
/**
 * Present only on the connect that traded a launch code.
 */
token: string | null, revisions: DisplayRevisions, };
