// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Library sidebar sections reachable through [`Action::OpenLibrary`].
 * Deliberately NOT advertised through the Lua `navigate()` API (unlike
 * [`NavTarget`]): adding rows there would expand the published plugin
 * surface.
 */
export type LibraryTarget = "Discover" | "RecentlyPlayed" | "Friends" | "Stats" | "PlaylistSync" | "LikedSongs" | "Albums" | "Artists" | "Podcasts" | "LocalFiles" | "AiDj";
