// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackInfo } from "./TrackInfo";

/**
 * Liked Songs cached from the top with no gap; `LoadMore(SavedTracks)` fetches the next page.
 */
export type LikedSongs = { tracks: Array<TrackInfo>, 
/**
 * The library's total as Spotify reports it; 0 before the first page.
 */
total: number, has_more: boolean, 
/**
 * False without a Spotify session: the list cannot load.
 */
available: boolean, 
/**
 * False until the first page landed; an empty list before that is still loading.
 */
loaded: boolean, };
