// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A paginated list surface [`Action::LoadMore`] can advance. Grows
 * additively as later screens adopt continuous pagination.
 */
export type ListTarget = "PlaylistTracks" | "SavedTracks" | "SavedAlbums" | "SavedShows" | "ShowEpisodes";
