// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyricLine } from "./LyricLine";

export type LyricsPayload = { 
/**
 * `not_started`, `loading`, `found` or `not_found`.
 */
status: string, 
/**
 * False when the line times are estimated from plain lyrics.
 */
synced: boolean, lines: Array<LyricLine>, };
