// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Surfaces reachable through [`Action::Navigate`].
 */
export type NavTarget = "Home" | "Queue" | "Settings" | "Devices" | "Help" | "Lyrics" | "RecentlyPlayed" | "Party" | "Analysis" | "MiniPlayer";
