// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NowPlaying = { title: string, artists: Array<string>, album: string, image_url: string | null, duration_ms: number, uri: string | null, is_playing: boolean, is_live: boolean, shuffle: boolean, repeat: string, };
