// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

export type OnboardingAsk = { "kind": "Line", prompt: string, secret: boolean, } | { "kind": "Confirm", title: string, body: string, question: string, } | { "kind": "PickSources", options: Array<Source>, };
