// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingQuestion } from "./OnboardingQuestion";

/**
 * Everything the page shows before boot: what was said so far, and the open question.
 */
export type OnboardingView = { transcript: string, pending: OnboardingQuestion | null, };
