// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingReplyAnswer } from "./OnboardingReplyAnswer";

/**
 * The page's answer to the question with the same `seq`.
 */
export type OnboardingReply = { seq: number, answer: OnboardingReplyAnswer, };
