// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

export type OnboardingReplyAnswer = { "kind": "Line", text: string, } | { "kind": "Confirm", yes: boolean, } | { "kind": "Sources", picked: Array<Source>, };
