// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingAsk } from "./OnboardingAsk";

export type OnboardingQuestion = { seq: number, ask: OnboardingAsk, };
