// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource deep-link [`Action::Open`] can address, by id.
 */
export type OpenTarget = { "Album": { id: string, from_search: boolean, } } | { "SavedAlbum": string } | { "Artist": { id: string, name: string, } } | { "Playlist": { id: string, from_search: boolean, } } | { "SourcePlaylist": string } | { "PlaylistFolder": number } | { "Show": string } | { "TrackAlbum": string };
