// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartyPhase } from "./PartyPhase";
import type { PartyRoom } from "./PartyRoom";

export type PartyPayload = { phase: PartyPhase, 
/**
 * Present while hosting or joined.
 */
room: PartyRoom | null, 
/**
 * False without a Spotify session: a party cannot start or join.
 */
available: boolean, };
