// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PartyRoom = { host: boolean, 
/**
 * Empty until the relay answers.
 */
code: string, 
/**
 * Empty until a guest's join lands.
 */
host_name: string, guests: Array<string>, 
/**
 * Guests may control playback; the host sets it.
 */
shared_control: boolean, };
