// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NowPlaying } from "./NowPlaying";

export type PlaybackPayload = { item: NowPlaying | null, volume: number, device: string | null, liked: boolean, };
