// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncLinkView } from "./SyncLinkView";

export type PlaylistSyncPayload = { links: Array<SyncLinkView>, 
/**
 * A run owns the sync slot.
 */
running: boolean, 
/**
 * The last finished run's summary; it covers only the links that run touched.
 */
last_summary: string | null, last_failed: boolean, };
