// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaylistInfo = { uri: string, name: string, 
/**
 * Owner display name (falls back to the owner id when no display name is set).
 */
owner: string, track_count: number, 
/**
 * Spotify base62 playlist id, when known.
 */
id: string | null, 
/**
 * Owner's base62 user id, when known. Used for ownership checks (the display
 * `owner` is not stable for comparison).
 */
owner_id: string | null, collaborative: boolean, public: boolean | null, image_url: string | null, };
