// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A size along one axis: an absolute cell count, or a percentage of the parent.
 */
export type PluginLength = { "Cells": number } | { "Percent": number };
