// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PopupLine } from "./PopupLine";

/**
 * A popup dialog produced by a plugin.
 */
export type PluginPopup = { title: string, lines: Array<PopupLine>, };
