// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginWidget } from "./PluginWidget";

/**
 * Retained content of a plugin custom screen. Screens are retained-mode by
 * design: draw runs with `&App` only (the engine is unreachable there), so
 * plugins publish content via effects and the renderer just reads it.
 */
export type PluginScreenContent = { title: string, widgets: Array<PluginWidget>, };
