// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginCoverArtFit } from "./PluginCoverArtFit";
import type { PluginWidget } from "./PluginWidget";
import type { PopupLine } from "./PopupLine";

/**
 * The content of a [`PluginWidget`]. `Row`/`Column` are pure layout containers:
 * they draw no border and no title, they only split their area.
 */
export type PluginWidgetKind = { "Paragraph": { lines: Array<PopupLine>, 
/**
 * Whether `PageUp`/`PageDown` scrolling applies to this paragraph.
 * Defaults to `true`, matching the `api_version = 5` behavior where every
 * paragraph on a screen scrolled in lockstep.
 */
scroll: boolean, } } | { "List": { title: string | null, items: Array<PopupLine>, 
/**
 * 0-based index of the highlighted item.
 */
selected: number | null, } } | { "Gauge": { 
/**
 * 0.0..=1.0 (clamped at the API layer).
 */
ratio: number, label: string | null, } } | { "CoverArt": { fit: PluginCoverArtFit, } } | { "Row": { children: Array<PluginWidget>, } } | { "Column": { children: Array<PluginWidget>, } };
