// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a [`PluginWidgetKind::CoverArt`] image is scaled into its area.
 *
 * `Crop` (CSS `cover`) is deliberately not offered: the terminal image
 * renderer documents that cropping overdraws characters over graphics and
 * that some terminals misbehave when it does (Alacritty's sixel branch is
 * named explicitly).
 */
export type PluginCoverArtFit = "Contain" | "Scale";
