// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginLength } from "./PluginLength";
import type { PluginWidgetKind } from "./PluginWidgetKind";

/**
 * A widget in a [`PluginScreenContent`].
 *
 * `width`/`height` are per-axis size hints; only the one matching the parent
 * container's axis is used (the top level is an implicit vertical stack).
 * `None` means "share the remaining space evenly".
 */
export type PluginWidget = { kind: PluginWidgetKind, width: PluginLength | null, height: PluginLength | null, };
