// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * A single line in a [`PluginPopup`].
 */
export type PopupLine = { text: string, fg: Color | null, bold: boolean, italic: boolean, };
