// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpisodeInfo } from "./EpisodeInfo";
import type { TrackInfo } from "./TrackInfo";

/**
 * A queue item as exposed to plugins. [`PlayableInfo`]'s externally-tagged
 * serde shape (`{ Track = {...} }`) is hostile to Lua, so queue items are
 * flattened into an explicit `kind` plus at most one populated payload field.
 */
export type QueueItemSnapshot = { 
/**
 * `"track"` or `"episode"`.
 */
kind: string, track: TrackInfo | null, episode: EpisodeInfo | null, };
