// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueSnapshot } from "./QueueSnapshot";
import type { TrackInfo } from "./TrackInfo";

export type QueuePayload = { spotify: QueueSnapshot, native: Array<TrackInfo>, now: TrackInfo | null, };
