// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueItemSnapshot } from "./QueueItemSnapshot";

/**
 * The playback queue as exposed to plugins.
 */
export type QueueSnapshot = { currently_playing: QueueItemSnapshot | null, items: Array<QueueItemSnapshot>, };
