// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An absolute repeat mode, mirroring Spotify's three states without the
 * rspotify type.
 */
export type RepeatSetting = "Off" | "Track" | "Context";
