// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where playback of an episode was last left off. Mirrors rspotify's
 * `ResumePoint`; carried so the episode list can render the "fully played"
 * marker and resume position.
 */
export type ResumePointInfo = { fully_played: boolean, resume_position_ms: number, };
