// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumInfo } from "./AlbumInfo";
import type { ArtistInfo } from "./ArtistInfo";
import type { PlaylistInfo } from "./PlaylistInfo";
import type { TrackInfo } from "./TrackInfo";

export type SearchPayload = { 
/**
 * False until a search landed; empty lists before that mean "not searched".
 */
ran: boolean, 
/**
 * The query the results answer; the page ignores results for an older query.
 */
query: string | null, tracks: Array<TrackInfo>, artists: Array<ArtistInfo>, albums: Array<AlbumInfo>, playlists: Array<PlaylistInfo>, 
/**
 * The Spotify track ids among `tracks` that are in Liked Songs.
 */
liked: Array<string>, };
