// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumPayload } from "./AlbumPayload";
import type { DeviceInfo } from "./DeviceInfo";
import type { DiscoverPayload } from "./DiscoverPayload";
import type { HelloPayload } from "./HelloPayload";
import type { LikedSongs } from "./LikedSongs";
import type { LyricsPayload } from "./LyricsPayload";
import type { OnboardingView } from "./OnboardingView";
import type { PartyPayload } from "./PartyPayload";
import type { PlaybackPayload } from "./PlaybackPayload";
import type { QueuePayload } from "./QueuePayload";
import type { SearchPayload } from "./SearchPayload";
import type { SessionPlay } from "./SessionPlay";
import type { SourcePayload } from "./SourcePayload";
import type { SourcePlaylists } from "./SourcePlaylists";
import type { StatsPayload } from "./StatsPayload";
import type { StatusPayload } from "./StatusPayload";

export type ServerMessage = { "kind": "hello", payload: HelloPayload, } | { "kind": "onboarding", payload: OnboardingView, } | { "kind": "tick", payload: number | null, } | { "kind": "playback", rev: number, payload: PlaybackPayload, } | { "kind": "queue", rev: number, payload: QueuePayload, } | { "kind": "party", rev: number, payload: PartyPayload, } | { "kind": "status", rev: number, payload: StatusPayload, } | { "kind": "source", rev: number, payload: SourcePayload, } | { "kind": "library", rev: number, payload: SourcePlaylists, } | { "kind": "liked", rev: number, payload: LikedSongs, } | { "kind": "theme", rev: number, payload: { [key in string]: [number, number, number] | null }, } | { "kind": "devices", rev: number, payload: Array<DeviceInfo>, } | { "kind": "search", rev: number, payload: SearchPayload, } | { "kind": "route", rev: number, payload: string, } | { "kind": "stats", rev: number, payload: StatsPayload, } | { "kind": "lyrics", rev: number, payload: LyricsPayload, } | { "kind": "album", rev: number, payload: AlbumPayload, } | { "kind": "session", rev: number, payload: Array<SessionPlay>, } | { "kind": "discover", rev: number, payload: DiscoverPayload, };
