// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceInfo } from "./DeviceInfo";
import type { HelloPayload } from "./HelloPayload";
import type { OnboardingView } from "./OnboardingView";
import type { PlaybackPayload } from "./PlaybackPayload";
import type { QueuePayload } from "./QueuePayload";
import type { StatusPayload } from "./StatusPayload";

export type ServerMessage = { "kind": "hello", payload: HelloPayload, } | { "kind": "onboarding", payload: OnboardingView, } | { "kind": "tick", payload: number | null, } | { "kind": "playback", rev: number, payload: PlaybackPayload, } | { "kind": "queue", rev: number, payload: QueuePayload, } | { "kind": "status", rev: number, payload: StatusPayload, } | { "kind": "theme", rev: number, payload: { [key in string]: [number, number, number] | null }, } | { "kind": "devices", rev: number, payload: Array<DeviceInfo>, } | { "kind": "route", rev: number, payload: string, };
