// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One finished play since this process started, for the Session screen.
 */
export type SessionPlay = { 
/**
 * Unix milliseconds.
 */
started_at_ms: number, ended_at_ms: number, listened_ms: number, 
/**
 * 0 for a live stream.
 */
duration_ms: number, title: string, artists: Array<string>, album: string, 
/**
 * The scheme names the source; `None` for a Spotify local file.
 */
uri: string | null, image_url: string | null, };
