// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShowInfo = { id: string | null, uri: string | null, name: string, description: string, 
/**
 * Show publisher (the "by …" attribution rendered in the podcast list).
 */
publisher: string, image_url: string | null, };
