// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields that can be used for sorting
 *
 * The serde derives on this enum, `SortOrder` and `SortContext` are the
 * action-vocabulary wire shape: `Action::Sort` carries them directly.
 */
export type SortField = "Default" | "Name" | "DateAdded" | "Artist" | "Duration" | "Album";
