// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

export type SourcePayload = { active: Source, 
/**
 * The sources compiled into this build, in display order.
 */
compiled: Array<Source>, };
