// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

/**
 * One source the first-run picker offers, with the text the terminal picker shows.
 */
export type SourceChoice = { source: Source, label: string, note: string, };
