// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsMovement = { name: string, 
/**
 * `climb`, `fall` or `new`.
 */
kind: string, from: number | null, 
/**
 * `None` for an artist the period never played.
 */
to: number | null, };
