// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusPayload = { message: string | null, is_error: boolean, api_error: string | null, };
