// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsRow = { title: string, 
/**
 * Tracks only.
 */
artist: string | null, 
/**
 * Tracks only.
 */
uri: string | null, listened_ms: number, 
/**
 * Artists only: 1-based, by listened time over all history.
 */
all_time_rank: number | null, 
/**
 * Artists only: the first listen falls inside the period.
 */
new: boolean, };
