// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodPlays } from "./PeriodPlays";
import type { StatsMovement } from "./StatsMovement";
import type { StatsRow } from "./StatsRow";

export type StatsPayload = { 
/**
 * `7d`, `30d`, `month`, `year` or `all`.
 */
period: string, loading: boolean, 
/**
 * False until a load for this period landed.
 */
loaded: boolean, 
/**
 * Every period's qualified plays, in the ring order of the period keys.
 */
plays: Array<PeriodPlays>, top_artists: Array<StatsRow>, top_albums: Array<StatsRow>, top_tracks: Array<StatsRow>, 
/**
 * The top five of the last 7 days, whatever the selected period.
 */
week_tracks: Array<StatsRow>, movements: Array<StatsMovement>, };
