// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";
import type { Unmatched } from "./Unmatched";

export type SyncMirrorView = { source: Source, 
/**
 * Tracks placed on the mirror; the match cache itself stays on the server.
 */
matched: number, unmatched: Array<Unmatched>, 
/**
 * RFC 3339; `null` for a mirror that never finished a run.
 */
last_run: string | null, };
