// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";
import type { SyncMirrorView } from "./SyncMirrorView";

export type SyncLinkView = { id: string, source: Source, name: string, mirrors: Array<SyncMirrorView>, 
/**
 * This link's line in the last run, which names a skipped or failed mirror.
 */
last_line: string | null, last_failed: boolean, };
