// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A [`Theme`] field addressed by name, one variant per struct field.
 *
 * This is the single source of truth coupling the runtime theme-override
 * surface (Lua `spotatui.set_theme`, `Action::SetTheme`) to the struct:
 * a new variant without a struct field breaks [`Theme::set`]'s exhaustive
 * match, and a new `Theme` field breaks the full destructuring at the top
 * of `set`, so either half added alone is a compile error where the old
 * parallel string whitelists silently dropped the write on a typo.
 */
export type ThemeField = "Active" | "Banner" | "ErrorBorder" | "ErrorText" | "Hint" | "Hovered" | "Inactive" | "PlaybarBackground" | "PlaybarProgress" | "PlaybarProgressText" | "PlaybarText" | "Selected" | "Text" | "Background" | "Header" | "HighlightedLyrics" | "AnalysisBar" | "AnalysisBarText";
