// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistRef } from "./ArtistRef";

export type TrackInfo = { uri: string | null, name: string, 
/**
 * Display artist names. Mirrors `artist_refs[*].name`; retained for the
 * `api_version = 4` scripting contract (plugins read `track.artists`).
 */
artists: Array<string>, 
/**
 * Display album name. Retained for the scripting contract.
 */
album: string, duration_ms: number, 
/**
 * Spotify base62 track id (`None` for local/unknown tracks).
 */
id: string | null, 
/**
 * Spotify base62 id of the track's album, when known.
 */
album_id: string | null, 
/**
 * Structured, navigable artist references (id + name). Populated when the
 * source provides per-artist data; empty when only a combined display string
 * is available (e.g. native-playback snapshots).
 */
artist_refs: Array<ArtistRef>, is_playable: boolean, is_local: boolean, track_number: number, explicit: boolean, 
/**
 * A directly-fetchable cover-art image URL for this track, when the source
 * can provide one (Subsonic getCoverArt, YouTube thumbnail, Qobuz album art). `None` for
 * sources without per-track art. Additive: only adds a key to the serialized
 * snapshot, preserving the api_version = 4 plugin contract.
 */
image_url: string | null, };
