// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackInfo } from "./TrackInfo";

/**
 * The track table rows; `uri` names the playlist they belong to, and is `null` while it loads.
 */
export type TrackTablePayload = { uri: string | null, tracks: Array<TrackInfo>, 
/**
 * `LoadMore(PlaylistTracks)` fetches the next page.
 */
has_more: boolean, };
