// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnmatchReason } from "./UnmatchReason";

/**
 * A master track the last run could not place on a mirror.
 */
export type Unmatched = { master_key: string, title: string, artist: string, reason: UnmatchReason, };
