// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a master track has no mirror track.
 */
export type UnmatchReason = "NoCandidate" | "NotSyncable" | { "SearchFailed": string };
