use crate::core::banner::BANNER;
use crate::core::onboarding::Onboarding;
use anyhow::{anyhow, Context, Error, Result};
use serde::{Deserialize, Serialize};
use std::{
  fs,
  io::Write,
  path::{Path, PathBuf},
};

const DEFAULT_PORT: u16 = 8888;
const FILE_NAME: &str = "client.yml";
const TOKEN_CACHE_FILE: &str = ".spotify_token_cache.json";
const GITIGNORE_FILE: &str = ".gitignore";
pub const NCSPOT_CLIENT_ID: &str = "d420a117a32841c2b3474932e49fb54b";
const AUTH_SETUP_VERSION: u8 = 2;

#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientConfig {
  pub client_id: String,
  #[serde(default)]
  pub fallback_client_id: Option<String>,
  #[serde(default)]
  pub client_secret: String,
  #[serde(default)]
  pub setup_version: u8,
  pub device_id: Option<String>,
  // FIXME: port should be defined in `user_config` not in here
  pub port: Option<u16>,
  // Streaming configuration
  #[serde(default = "default_streaming_enabled")]
  pub enable_streaming: bool,
  #[serde(default = "default_device_name")]
  pub streaming_device_name: String,
  #[serde(default = "default_bitrate")]
  pub streaming_bitrate: u16,
  #[serde(default)]
  pub streaming_audio_cache: bool,
}

fn default_streaming_enabled() -> bool {
  cfg!(feature = "streaming")
}

fn default_device_name() -> String {
  "spotatui".to_string()
}

fn default_bitrate() -> u16 {
  320
}

pub struct ConfigPaths {
  pub config_file_path: PathBuf,
  pub token_cache_path: PathBuf,
}

impl ClientConfig {
  pub fn new() -> ClientConfig {
    ClientConfig {
      client_id: "".to_string(),
      fallback_client_id: None,
      client_secret: "".to_string(),
      setup_version: 0,
      device_id: None,
      port: None,
      enable_streaming: default_streaming_enabled(),
      streaming_device_name: default_device_name(),
      streaming_bitrate: default_bitrate(),
      streaming_audio_cache: false,
    }
  }

  pub fn get_redirect_uri(&self) -> String {
    format!("http://127.0.0.1:{}/callback", self.get_port())
  }

  pub fn get_port(&self) -> u16 {
    self.port.unwrap_or(DEFAULT_PORT)
  }

  pub fn get_or_build_paths(&self) -> Result<ConfigPaths> {
    match (
      crate::core::paths::app_config_dir(),
      crate::core::paths::app_state_dir(),
    ) {
      (Some(app_config_dir), Some(app_state_dir)) => {
        fs::create_dir_all(&app_config_dir)?;
        crate::core::paths::ensure_private_dir(&app_state_dir)?;

        // Create .gitignore to protect sensitive config from being committed.
        let gitignore_path = app_config_dir.join(GITIGNORE_FILE);
        if !gitignore_path.exists() {
          let gitignore_content = "\
            # Protect sensitive files from being committed
            # This file is auto-generated by spotatui

            # Client credentials (client_id, client_secret)
            client.yml
            ";
          fs::write(&gitignore_path, gitignore_content)?;
        }

        let config_file_path = &app_config_dir.join(FILE_NAME);
        let token_cache_path = &app_state_dir.join(TOKEN_CACHE_FILE);
        if let Err(error) =
          migrate_legacy_token_caches_if_unclaimed(&app_config_dir, &app_state_dir)
        {
          log::warn!(
            "failed to migrate legacy Spotify token cache from {} to {}: {error}",
            app_config_dir.display(),
            app_state_dir.display()
          );
        }

        let paths = ConfigPaths {
          config_file_path: config_file_path.to_path_buf(),
          token_cache_path: token_cache_path.to_path_buf(),
        };

        Ok(paths)
      }
      _ => Err(anyhow!("No $HOME directory found for client config/state")),
    }
  }

  pub fn set_device_id(&mut self, device_id: String) -> Result<()> {
    let paths = self.get_or_build_paths()?;
    let config_string = fs::read_to_string(&paths.config_file_path)?;
    let mut config_yml: ClientConfig = serde_yaml::from_str(&config_string)?;

    self.device_id = Some(device_id.clone());
    config_yml.device_id = Some(device_id);

    let new_config = serde_yaml::to_string(&config_yml)?;
    let mut config_file = fs::File::create(&paths.config_file_path)?;
    write!(config_file, "{}", new_config)?;
    Ok(())
  }

  /// Load `client.yml`, or run the auth wizard when the file is absent.
  /// Returns `true` when the wizard ran.
  pub fn load_config(&mut self, onboarding: &dyn Onboarding) -> Result<bool> {
    let paths = self.get_or_build_paths()?;
    if paths.config_file_path.exists() {
      let config_string = fs::read_to_string(&paths.config_file_path)?;
      let config_yml: ClientConfig = serde_yaml::from_str(&config_string)?;

      self.client_id = config_yml.client_id;
      self.fallback_client_id = config_yml.fallback_client_id;
      self.client_secret = config_yml.client_secret;
      self.setup_version = config_yml.setup_version;
      self.device_id = config_yml.device_id;
      self.port = config_yml.port;
      self.enable_streaming = config_yml.enable_streaming;
      self.streaming_device_name = config_yml.streaming_device_name;
      self.streaming_bitrate = config_yml.streaming_bitrate;
      self.streaming_audio_cache = config_yml.streaming_audio_cache;

      Ok(false)
    } else {
      onboarding.info(BANNER);

      onboarding.info(&format!(
        "Config will be saved to {}",
        paths.config_file_path.display()
      ));

      self.run_auth_setup_wizard(onboarding)?;
      Ok(true)
    }
  }

  pub fn needs_auth_setup_migration(&self) -> bool {
    self.setup_version < AUTH_SETUP_VERSION
  }

  pub fn reconfigure_auth(&mut self, onboarding: &dyn Onboarding) -> Result<()> {
    self.run_auth_setup_wizard(onboarding)
  }

  /// Write `client.yml` with ncspot defaults but WITHOUT running the OAuth flow.
  /// Used when a first-run user picks a free source: it seeds a `client_id`/port
  /// so a later in-TUI Spotify login can build the authorize URL, while doing no
  /// browser flow now. `load_config` then finds the file and skips the wizard.
  pub fn init_default_spotify_config(&mut self) -> Result<()> {
    self.client_id = NCSPOT_CLIENT_ID.to_string();
    self.fallback_client_id = None;
    self.client_secret = String::new();
    self.port = Some(8989);
    self.setup_version = AUTH_SETUP_VERSION;
    self.save_config_file()
  }

  pub fn mark_auth_setup_migrated(&mut self) -> Result<()> {
    self.setup_version = AUTH_SETUP_VERSION;
    self.save_config_file()
  }

  fn run_auth_setup_wizard(&mut self, onboarding: &dyn Onboarding) -> Result<()> {
    onboarding.info("\nClient setup options:\n");
    onboarding
      .info("  1) Use ncspot client ID (quick setup, may break if Spotify revokes shared access)");
    onboarding
      .info("  2) Use ncspot client ID + your own fallback app ID (recommended for resilience)");

    let setup_option = ClientConfig::get_setup_option(onboarding)?;

    let (client_id, fallback_client_id) = match setup_option {
      1 => {
        onboarding.info("\nUsing ncspot redirect URI: http://127.0.0.1:8989/login");
        (NCSPOT_CLIENT_ID.to_string(), None)
      }
      2 => {
        onboarding.info("\nCreate your fallback Spotify app:\n");
        let instructions = [
          "Go to https://developer.spotify.com/dashboard/applications",
          "Click `Create app` and add your own name and description",
          &format!(
            "Add `http://127.0.0.1:{}/callback` to Redirect URIs",
            DEFAULT_PORT
          ),
        ];

        for (number, item) in instructions.iter().enumerate() {
          onboarding.info(&format!("  {}. {}", number + 1, item));
        }

        let fallback = ClientConfig::get_client_key_from_input("Fallback Client ID", onboarding)?;
        (NCSPOT_CLIENT_ID.to_string(), Some(fallback))
      }
      _ => unreachable!(),
    };

    let port = if setup_option == 1 {
      8989
    } else {
      let port = onboarding.prompt_line(&format!(
        "\nEnter port of fallback redirect uri (default {}): \n",
        DEFAULT_PORT
      ))?;
      port.trim().parse::<u16>().unwrap_or(DEFAULT_PORT)
    };

    self.client_id = client_id;
    self.fallback_client_id = fallback_client_id;
    self.client_secret = String::new();
    self.port = Some(port);
    self.setup_version = AUTH_SETUP_VERSION;

    self.save_config_file()
  }

  fn save_config_file(&self) -> Result<()> {
    let paths = self.get_or_build_paths()?;
    let content_yml = serde_yaml::to_string(self)?;

    let mut config_file = fs::File::create(&paths.config_file_path)?;
    write!(config_file, "{}", content_yml)?;
    Ok(())
  }

  fn get_client_key_from_input(
    type_label: &'static str,
    onboarding: &dyn Onboarding,
  ) -> Result<String> {
    const MAX_RETRIES: u8 = 5;
    let mut num_retries = 0;
    loop {
      let input = onboarding.prompt_line(&format!("\nEnter your {}: \n", type_label))?;
      let client_key = input.trim().to_string();
      match ClientConfig::validate_client_key(&client_key) {
        Ok(_) => return Ok(client_key),
        Err(error_string) => {
          onboarding.info(&error_string.to_string());
          num_retries += 1;
          if num_retries == MAX_RETRIES {
            return Err(Error::from(std::io::Error::other(format!(
              "Maximum retries ({}) exceeded.",
              MAX_RETRIES
            ))));
          }
        }
      };
    }
  }

  fn get_setup_option(onboarding: &dyn Onboarding) -> Result<u8> {
    const MAX_RETRIES: u8 = 5;
    let mut retries = 0;

    loop {
      let input = onboarding.prompt_line("\nChoose option (1 or 2): \n")?;
      let trimmed = input.trim();

      match trimmed.parse::<u8>() {
        Ok(1) | Ok(2) => return Ok(trimmed.parse::<u8>()?),
        _ => {
          onboarding.info("Invalid choice. Please enter 1 or 2.");
          retries += 1;
          if retries >= MAX_RETRIES {
            return Err(Error::from(std::io::Error::other(format!(
              "Maximum retries ({}) exceeded.",
              MAX_RETRIES
            ))));
          }
        }
      }
    }
  }

  fn validate_client_key(key: &str) -> Result<()> {
    const EXPECTED_LEN: usize = 32;
    if key.len() != EXPECTED_LEN {
      Err(Error::from(std::io::Error::new(
        std::io::ErrorKind::InvalidInput,
        format!("invalid length: {} (must be {})", key.len(), EXPECTED_LEN,),
      )))
    } else if !key.chars().all(|c| c.is_ascii_hexdigit()) {
      Err(Error::from(std::io::Error::new(
        std::io::ErrorKind::InvalidInput,
        "invalid character found (must be hex digits)",
      )))
    } else {
      Ok(())
    }
  }
}

fn migrate_legacy_token_caches_if_unclaimed(
  app_config_dir: &Path,
  app_state_dir: &Path,
) -> Result<()> {
  // OAuth tokens used to live next to client.yml; preserve them when moving
  // app-managed state out of the config directory.
  crate::core::migrations::migrate_legacy_path_if_unclaimed(
    &app_config_dir.join(TOKEN_CACHE_FILE),
    &app_state_dir.join(TOKEN_CACHE_FILE),
  )?;

  for entry in
    fs::read_dir(app_config_dir).with_context(|| format!("reading {}", app_config_dir.display()))?
  {
    let entry = entry?;
    let file_name = entry.file_name();
    let Some(file_name) = file_name.to_str() else {
      continue;
    };

    if file_name == TOKEN_CACHE_FILE || !is_client_token_cache_file(file_name) {
      continue;
    }

    crate::core::migrations::migrate_legacy_path_if_unclaimed(
      &entry.path(),
      &app_state_dir.join(file_name),
    )?;
  }

  Ok(())
}

fn is_client_token_cache_file(file_name: &str) -> bool {
  file_name.starts_with(".spotify_token_cache_") && file_name.ends_with(".json")
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::core::test_helpers::ScriptedOnboarding;

  #[test]
  fn setup_option_accepts_a_valid_choice_after_garbage() {
    let onboarding = ScriptedOnboarding::with_answers(&["x", "2"]);
    assert_eq!(ClientConfig::get_setup_option(&onboarding).unwrap(), 2);
    assert!(onboarding.saw("Invalid choice. Please enter 1 or 2."));
  }

  #[test]
  fn setup_option_errors_after_max_retries() {
    let onboarding = ScriptedOnboarding::with_answers(&["x", "0", "3", "", "yes"]);
    assert!(ClientConfig::get_setup_option(&onboarding).is_err());
  }

  #[test]
  fn client_key_prompt_rejects_bad_keys_until_a_valid_one() {
    let valid = "0123456789abcdef0123456789abcdef";
    let onboarding = ScriptedOnboarding::with_answers(&["tooshort", valid]);
    assert_eq!(
      ClientConfig::get_client_key_from_input("Fallback Client ID", &onboarding).unwrap(),
      valid
    );
    assert!(onboarding.saw("\nEnter your Fallback Client ID: \n"));
  }

  #[test]
  fn legacy_token_cache_migration_moves_base_and_client_token_files() {
    let dir = tempfile::tempdir().unwrap();
    let config_dir = dir.path().join("config");
    let state_dir = dir.path().join("state");
    std::fs::create_dir_all(&config_dir).unwrap();

    std::fs::write(config_dir.join(TOKEN_CACHE_FILE), "base token").unwrap();
    std::fs::write(
      config_dir.join(".spotify_token_cache_d420a117.json"),
      "client token",
    )
    .unwrap();
    std::fs::write(config_dir.join("client.yml"), "client_id: abc").unwrap();

    migrate_legacy_token_caches_if_unclaimed(&config_dir, &state_dir).unwrap();

    assert!(!config_dir.join(TOKEN_CACHE_FILE).exists());
    assert!(!config_dir
      .join(".spotify_token_cache_d420a117.json")
      .exists());
    assert_eq!(
      std::fs::read_to_string(state_dir.join(TOKEN_CACHE_FILE)).unwrap(),
      "base token"
    );
    assert_eq!(
      std::fs::read_to_string(state_dir.join(".spotify_token_cache_d420a117.json")).unwrap(),
      "client token"
    );
    assert!(config_dir.join("client.yml").exists());
  }

  #[test]
  fn legacy_token_cache_migration_does_not_overwrite_existing_state_token() {
    let dir = tempfile::tempdir().unwrap();
    let config_dir = dir.path().join("config");
    let state_dir = dir.path().join("state");
    std::fs::create_dir_all(&config_dir).unwrap();
    std::fs::create_dir_all(&state_dir).unwrap();

    std::fs::write(
      config_dir.join(".spotify_token_cache_d420a117.json"),
      "legacy token",
    )
    .unwrap();
    std::fs::write(
      state_dir.join(".spotify_token_cache_d420a117.json"),
      "state token",
    )
    .unwrap();

    migrate_legacy_token_caches_if_unclaimed(&config_dir, &state_dir).unwrap();

    assert_eq!(
      std::fs::read_to_string(config_dir.join(".spotify_token_cache_d420a117.json")).unwrap(),
      "legacy token"
    );
    assert_eq!(
      std::fs::read_to_string(state_dir.join(".spotify_token_cache_d420a117.json")).unwrap(),
      "state token"
    );
  }
}
